title: Catalex Bio Technical Notes
description: Technical summaries and application notes for industrial enzymes.

# GitHub Pages URL structure
baseurl: "/application-of-enzymes"         # IMPORTANT: your repo name
url: "https://catalexbio-enzymes.github.io" # your GitHub Pages root

# Theme
theme: jekyll-theme-cayman
markdown: kramdown

# Make custom CSS load
include:
  - assets/css/custom.css
