title: Catalex Bio Technical Notes
description: Technical summaries and application notes on industrial enzymes from Catalex Bio.
baseurl: "/application-of-enzymes"   # the subpath for your Pages site
url: "https://catalexbio-enzymes.github.io"  # GitHub Pages root URL
theme: jekyll-theme-cayman
markdown: kramdown
plugins: []
exclude:
  - README.md
