title: Catalex Bio Technical Notes
description: Technical summaries and application notes for industrial enzymes.
baseurl: "/application-of-enzymes"
url: "https://catalexbio-enzymes.github.io"
theme: jekyll-theme-cayman
markdown: kramdown

include:
  - assets/css/custom.css
